config/routes.rb
Rails.application.routes.draw do
  resources :films
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "films#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #sends to path after logout button
    private
    def after_sign_out_path_for(resources_or_scope)
        new_user_session_path
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /films
  # GET /films.json
  def index
    # @films = Film.all
    if params[:search].blank?
      @views = "No value entered"
      response = HTTParty.get('https://swapi.co/api/films/')
      # byebug
      @films = JSON.parse(response.body)
    else
      @views = params[:search]
      response = HTTParty.get("https://swapi.co/api/films/?search=#{@views}")
      @films = JSON.parse(response.body)
    end 
  end

  # GET /films/1
  # GET /films/1.json
  def show
    episode_id = params[:id]
    response = HTTParty.get("https://swapi.co/api/films/?episode_id=#{episode_id}")
    @before = JSON.parse(response.body)
    @film = @before["results"][0]

    # loop for characters
    @charactersArray = []
    @before["results"][0]["characters"].each do |item|
      reqChar = HTTParty.get(item)
      @resChar = JSON.parse(reqChar.body)
      @charactersArray.push(@resChar)
    end
    
  end

  # GET /films/new
  def new
    # @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    # @film = Film.new(film_params)

    # respond_to do |format|
    #   if @film.save
    #     format.html { redirect_to @film, notice: 'Film was successfully created.' }
    #     format.json { render :show, status: :created, location: @film }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @film.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    # respond_to do |format|
    #   if @film.update(film_params)
    #     format.html { redirect_to @film, notice: 'Film was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @film }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @film.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    # @film.destroy
    # respond_to do |format|
    #   format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      # @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      # params.require(:film).permit(:title, :opening_crawl, :director, :producer, :release_date, :characters, :planets, :starships, :vehicles, :species, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :opening_crawl %>
    <%= form.text_area :opening_crawl %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :characters %>
    <%= form.text_field :characters %>
  </div>

  <div class="field">
    <%= form.label :planets %>
    <%= form.text_field :planets %>
  </div>

  <div class="field">
    <%= form.label :starships %>
    <%= form.text_field :starships %>
  </div>

  <div class="field">
    <%= form.label :vehicles %>
    <%= form.text_field :vehicles %>
  </div>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<div id="alertDisplay">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  A film has been added to your list of favourites.
</div>

<div class="ui segment">
  <h1>Films</h1>

  <%= form_tag(root_path, method: "get") do %>
    <div class="ui form segment">
      <div class="field">
        <%= label_tag(:search, "Search") %>
        <%= text_field_tag(:search) %>
      </div>
      <div class="actions">
        <%= submit_tag "Search", { :class=>"ui blue button" } %>
      </div>
      <% if params[:search] != nil %>
        <h2>Value you entered for search</h2>
        <p><%= @views %></p>
      <% end %>
    </div>
  <% end %>
  

  <%# favourite table %>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>Favourites</th>
        <th>Remove film from favourites</th>
      </tr>
    </thead>
    <tbody id="favourites">
    </tbody>
  </table>

  <%# all films table %>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>Film title</th>
        <th>Add film to favourites</th>
        <th>View film</th>
      </tr>
    </thead>
    <tbody>
      <% @films["results"].each do |film| %>
        <tr>
          <td><%= film["title"] %></td>
          <td><button class="ui green button" onClick="favouriteMe('<%= film["title"] %>',1)">Favourite Me</button></td>
          <td><%= link_to 'Show', film_path(film["episode_id"]),
              { :class=>"ui blue button" }  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

<%# <%= link_to 'New Film', new_film_path %>

<script>favOnLoad();</script>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui segment">
  <h1>Film information</h1>

  <p class="ui segment">
    <strong>Title:</strong>
    <%= @film["title"] %>
  </p>

  <p class="ui segment">
    <strong>Opening crawl:</strong>
    <%= @film["opening_crawl"] %>
  </p>

  <p class="ui segment">
    <strong>Director:</strong>
    <%= @film["director"] %>
  </p>

  <p class="ui segment">
    <strong>Producer:</strong>
    <%= @film["producer"] %>
  </p>

  <p class="ui segment">
    <strong>Release date:</strong>
    <%= @film["release_date"] %>
  </p>

  <div class="ui segment">
    <strong>Characters:</strong>
    <% @charactersArray.each do |char| %>
      <div class="tooltip"><%= char["name"] %>
        <table class="tooltiptext">
          <thead>
          <tbody>
              <tr><td>Name:</td><td><%= char["name"]  %></td></tr>
              <tr><td>Height:</td><td><%= char["height"]  %></td></tr>
              <tr><td>Mass:</td><td><%= char["mass"]  %></td></tr>
              <tr><td>Hair colour:</td><td><%= char["hair_color"]  %></td></tr>
              <tr><td>Skin colour:</td><td><%= char["skin_color"]  %></td></tr>
              <tr><td>Eye colour:</td><td><%= char["eye_color"]  %></td></tr>
              <tr><td>Birth year:</td><td><%= char["birth_year"]  %></td></tr>
              <tr><td>Gender:</td><td><%= char["gender"]  %></td></tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
  

  <p class="ui segment">
    <strong>Planets:</strong>
    <%= @film["planets"] %>
  </p>

  <p class="ui segment">
    <strong>Starships:</strong>
    <%= @film["starships"] %>
  </p>

  <p class="ui segment">
    <strong>Vehicles:</strong>
    <%= @film["vehicles"] %>
  </p>

  <p class="ui segment">
    <strong>Species:</strong>
    <%= @film["species"] %>
  </p>

  <div className="ui clear"></div>
  <div className="ui clear"></div>

  <%= link_to 'Back to home', films_path, { :class=>"ui yellow button" } %>

</div>

app/views/generic/_header.html.erb
<header>    
    <% if user_signed_in? %>
        <span><%= link_to "Home", root_path %></span>
        <span> | <%= current_user.email %></span>
        <%# <span> | <%= link_to "My Profile", product_listings_path %>
        <%# </span> %>
        <span> | <%= link_to "logout", destroy_user_session_path, method: "DELETE" %></span>
    <% else %>
        <div class="nav">
            <div class = "buttons">
                <%= link_to 'Home', root_path %>
                <button type="button" class="btn btn-primary btn-sm" > <%=  link_to "Log in", new_user_session_path %></button>
                <button type="button" class="btn btn-primary btn-sm"><%= link_to "Sign up", new_user_registration_path %></button>
            </div>
        </div>
    <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarwarsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'favourite' %>
  </head>

  <body>
    <div className="ui container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if user_signed_in? %>
        <%= render "generic/header" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>